### ISSUE TITLE
Add doxygen generated docs to sphinx

### ISSUE THREAD

**Issue by tammyleino** [OpenAMP/openamp-docs#9]
@wmamills Will generate a bundle and upload to a common location where we can link from.  Long term goal is to generate the docs with each check-in to openamp repo so these docs can be updated dynamically.

**Comment by wmamills** [comment]
I have a first draft of this in PR #17 
It builds on each commit to the docs repo.
I found a way to publish all via readthedocs.

**Comment by wmamills** [comment]
PR #17 closed this
